# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-17 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='title_img',
            field=models.FileField(default='avatar/house/default.png', null=True, upload_to='avatar/house/', verbose_name='标题图片'),
        ),
        migrations.AddField(
            model_name='house',
            name='trading_area',
            field=models.CharField(max_length=64, null=True, verbose_name='商圈'),
        ),
    ]
