# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-19 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0002_auto_20190317_0047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housingcharacteristics',
            options={'verbose_name': '房源特色表', 'verbose_name_plural': '房源特色表'},
        ),
        migrations.AlterField(
            model_name='broker',
            name='phone',
            field=models.BigIntegerField(help_text='用于手机验证码登录', null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='house',
            name='floor_type',
            field=models.IntegerField(choices=[(0, '低楼层'), (1, '中楼层'), (2, '高楼层'), (3, '顶层'), (4, '底层')], default=0, null=True, verbose_name='楼层位置'),
        ),
    ]
